// <auto-generated />
namespace DOAN_WEBNC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _update_column_namhoc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_update_column_namhoc));
        
        string IMigrationMetadata.Id
        {
            get { return "202007151631218__update_column_namhoc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
