// <auto-generated />
namespace DOAN_WEBNC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _EditColumnMSSV : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_EditColumnMSSV));
        
        string IMigrationMetadata.Id
        {
            get { return "202007100834501__EditColumnMSSV"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
